### ISSUE TITLE
dotnet tool restore femto results in a nuget error: The repository primary signature validity period has expired.

### ISSUE THREAD

**Issue by kurt-mueller-osumc** [Zaid-Ajaj/Femto#85]
Currently I can't restore the femto tool:

```
% dotnet tool restore
warning NU3028: Package 'Femto 0.9.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.
error NU3037: Package 'Femto 0.9.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired.

Package "femto" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
   at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
   at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
```

**Comment by Zaid-Ajaj** [comment]
I don't know why v0.9.0 can't be restored to be honest. Can you try restoring the latest version?

**Comment by kurt-mueller-osumc** [comment]
Sure! I just downloaded the news SAFE Stack template and followed the "Quick Start" instructions.

**Comment by kurt-mueller-osumc** [comment]
Hey Zaid, it successfully restores but with a warning:

```
 dotnet tool restore
warning NU3028: Package 'Femto 0.12.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.
```

**Comment by Zaid-Ajaj** [comment]
@kurt-mueller-osumc Femto is published to the official package registry `https://api.nuget.org/v3/index.json` and according to your warning, it says there is an "ExplicitDistrust" so I assume this is something from your own system. 

Please re-open the issue if you believe that is not the case
